services:
  nodejs:
    build:
      context: ./
      dockerfile: Dockerfile
    volumes:
      - ./:/workspaces
    ports:
      - 3000:3000
      - 6006:6006
    tty: true
    platform: linux/x86_64